stages:
  - containerization
  - deploy

variables:
  APPLICATION_NAME: cms
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CERTIFICATE_DOMAIN: api.cms.maximemoreillon.com

containerization:
  stage: containerization
  script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Building the container image
    - docker build -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME} .
    # Pushing the image to the registry
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
    # Cleanup
    - docker image rm ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

deployment:
  stage: deploy
  script:
    # create/update the deployment
    - envsubst < deployment.yml | kubectl apply -f -
    # Pull latest image of deployment
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE} # KUBERNETES_NAMESPACE provided by GitLab
