stages:
  - containerization
  - deploy

variables:
  DOCKER_IMAGE: 192.168.1.2:5000/cms
  KUBERNETES_DEPLOYMENT: cms


containerization:
  stage: containerization
  script:
    - cp ${SECRETS} ./secrets.js
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE}

deployment:
  stage: deploy
  script:
    - kubectl apply -f deployment.yml
    - kubectl rollout restart deployment/${KUBERNETES_DEPLOYMENT}
  environment:
    name: production
