stages:
  - containerization
  - deploy

variables:
  APPLICATION_NAME: cms


containerization:
  stage: containerization
  script:
    - cp ${SECRETS} ./secrets.js
    - docker build -t ${DOCKER_IMAGE} .
    - >
      docker build
      --build-arg HTTP_PROXY=$HTTP_PROXY
      --build-arg HTTPS_PROXY=$HTTPS_PROXY
      -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
      .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
    - docker image rm ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

deployment:
  stage: deploy
  script:
    - kubectl apply -f deployment.yml
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
