apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-deployment
  template:
    metadata:
      labels:
        app: cms-deployment
    spec:
      containers:
      - name: cms
        image: moreillon/cms
        ports:
        - containerPort: 8050
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cms-service
  name: cms-service
spec:
  ports:
  - port: 8050
    nodePort: 30050
  selector:
    app: cms-deployment
  type: LoadBalancer
