
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
      - name: cms
        image: ${CONTAINER_REGISTRY}/cms
        ports:
        - containerPort: 8050
---
apiVersion: v1
kind: Service
metadata:
  name: cms
spec:
  type: NodePort
  ports:
  - port: 8050
    nodePort: 30050
  selector:
    app: cms
---
# Service to make Neo4J (outside cluster) accessible
kind: Service
apiVersion: v1
metadata:
 name: neo4j
spec:
 ports:
 - port: 7687
   targetPort: 7687
---
# Endpoint for Neo4J service
kind: Endpoints
apiVersion: v1
metadata:
 name: neo4j
subsets:
 - addresses:
     - ip: 10.1.37.1
   ports:
     - port: 7687
