
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
      - name: cms
        image: ${CONTAINER_REGISTRY}/${APPLICATION_NAME} # CONTAINER_REGISTRY provided by GitLab
        imagePullPolicy: Always # Ensures that k8s pulls a new image on restart
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cms
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30050
  selector:
    app: cms
